### ISSUE TITLE
Please think abut publishing your addon to the ioBroker community

### ISSUE THREAD

**Issue by DutchmanNL** [Vertumnus/ioBroker.googleauth#1]
Hi, awesome this looks very cool !
Would be great if you would add this to the ioBroker repository's so everyone can see and install it by the admin

[Please have a look here](https://github.com/ioBroker/ioBroker.repositories/blob/master/README.md)

Kind regards,

Dutchman

**Comment by Vertumnus** [comment]
Hi @DutchmanNL,

I've already thought about, but not taken the time to do it. Today it is the day and my pull request for the latest repository is created (as well as for my other connected adapter: ioBroker.weblogin).

Thank you for pushing me this way ;-)

**Comment by DutchmanNL** [comment]
> Thank you for pushing me this way ;-)

great, now all ioBroker users will be able to see and use this cool development, thank you !
