### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [Vertumnus/ioBroker.googleauth#2]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/Vertumnus/ioBroker.googleauth

- [x] [E019] Invalid repository URL: github:Vertumnus/ioBroker.googleauth. Expected: git+https://github.com/Vertumnus/ioBroker.googleauth.git
- [x] [E112] extIcon must be the same as an icon but with github path
- [x] [E145] No news found for actual version 0.3.2
- [x] [E150] No common.connectionType found in io-package.json
- [x] [E152] No common.dataSource found in io-package.json
- [x] [E300] Not found on travis. Please setup travis
- [x] [E802] No topics found in the repository. Please go to "https://github.com/Vertumnus/ioBroker.googleauth", press the settings button beside the about title and add some topics.
- [x] [E603] NO "## Changelog" found in README.md

I have also found warnings that may be fixed if possible.

- [ ] [W801] .npmignore not found

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by Vertumnus** [comment]
Fixed
